$NetBSD: patch-Cargo.toml,v 1.1 2019/01/05 03:01:30 tnn Exp $

Need to wire down webdriver because 0.38.1 broke the API

--- Cargo.toml.orig	2018-10-04 13:03:45.000000000 +0000
+++ Cargo.toml
@@ -23,7 +23,7 @@ serde = "1.0"
 serde_json = "1.0"
 serde_derive = "1.0"
 uuid = { version = "0.5", features = ["v4"] }
-webdriver = "0.38.0"
+webdriver = "=0.38.0"
 zip = "0.4"
 
 [[bin]]
