listen_addresses = ['127.0.0.1:53', '[::1]:53']

ipv4_servers = true
ipv6_servers = true

require_nolog = true
require_nofilter = true

dnscrypt_servers = true
doh_servers = false

fallback_resolver = '1.1.1.1:53'
ignore_system_dns = true

use_syslog = true

[sources]
	[sources.'public-resolvers']
	url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
	cache_file = 'public-resolvers.md'
	minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
	refresh_delay = 72
	prefix = ''
